# Generated by Django 3.2.8 on 2021-10-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('unit_id', models.IntegerField()),
                ('category_id', models.IntegerField()),
            ],
        ),
    ]
